resolver: lts-7.19
packages:
- location: .
- location: ../../concur/
  #  git: https://github.com/ajnsit/concur
  #  commit: ba9d2a02498d691a4562982b1755a508b487f747
  extra-dep: true
  subdirs:
    - concur-core
    - concur-react
extra-deps:
- natural-transformation-0.4
- ghcjs-base-stub-0.1.0.3
flags: {}
extra-package-dbs: []
